// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { GameState } from "./tables/GameState.sol";
import { Line } from "./tables/Line.sol";
import { Player, PlayerData } from "./tables/Player.sol";
import { Entity, EntityData } from "./tables/Entity.sol";
import { UsernameHash } from "./tables/UsernameHash.sol";
import { LineOffchain } from "./tables/LineOffchain.sol";
import { UsernameOffchain } from "./tables/UsernameOffchain.sol";
