// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IAccessSystem } from "./IAccessSystem.sol";
import { IAdminSystem } from "./IAdminSystem.sol";
import { IDirectionSystem } from "./IDirectionSystem.sol";
import { IJumpSystem } from "./IJumpSystem.sol";
import { ISpawnSystem } from "./ISpawnSystem.sol";
import { IUtilitiesSystem } from "./IUtilitiesSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAccessSystem,
  IAdminSystem,
  IDirectionSystem,
  IJumpSystem,
  ISpawnSystem,
  IUtilitiesSystem
{}
